### ISSUE TITLE
Chat Messages send as the channel the stream is displaying

### ISSUE THREAD

**Issue by smolDev-ai** [digital-ronin/oc-twitch-plugin#4]
So, I'm using this plugin for a site, and I wanted to have the chat displayed. However, I was testing it earlier (after fixing it so that the chat didn't throw a 'sameorigin' x-frame-option error from twitch), and instead of being logged into _my_ account, I was looged into the channel I was watching's account. 

That is one huge hole that I don't know how to fix.

**Comment by danielbruni** [comment]
Sorry for the late Reply. Iam looking into this.

**Comment by danielbruni** [comment]
Fixed with 3657380dd09eb0433def8ad8126c891fddd4776d
